name: MediaCenter
services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurg
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:9999/dav/version.txt || exit 1
    ports:
      - "9999:9999"
    volumes:
      - ./zurg.yml:/app/config.yml
      - zurg_data:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - PUID=${RCLONE_UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ${ROOT_DIR}/data/realdebrid-zurg:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    healthcheck:
      test: sh -c "[ -f /data/version.txt ]"
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: "mount zurg: /data --allow-non-empty --allow-other --uid=${RCLONE_UID} --gid=${MEDIACENTER_GID} --umask=002 --dir-cache-time 10s --vfs-cache-mode full"

  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    environment:
      - PUID=${RDTCLIENT_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    ports:
      - "6500:6500"
    volumes:
      - ${ROOT_DIR}/data:/data
      - ${ROOT_DIR}/config/rdt-config:/data/db
    restart: unless-stopped
    depends_on:
      - rclone
    logging:
      driver: json-file
      options:
        max-size: 10m

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${SONARR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/sonarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      - rclone


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${RADARR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/radarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    depends_on:
      - rclone

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: ${RECYCLARR_UID}:${MEDIACENTER_GID}
    volumes:
      - ${ROOT_DIR}/config/recyclarr-config:/config
    environment:
      - TZ=${TIMEZONE}
      - RECYCLARR_CREATE_CONFIG=true
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PROWLARR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    depends_on:
      - rclone

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${OVERSEERR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - prowlarr

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PLEX_UID}
      - PGID=${MEDIACENTER_GID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_DIR}/config/plex-config:/config
      - ${ROOT_DIR}/data:/data
    restart: unless-stopped
    depends_on:
      - rclone

  autoscan:
    image: cloudb0x/autoscan:latest
    container_name: autoscan
    environment:
      - PUID=${AUTOSCAN_UID}
      - PGID=${MEDIACENTER_GID}
      - AUTOSCAN_VERBOSITY=0
    volumes:
      - ${ROOT_DIR}/config/autoscan-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - "3030:3030"
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - plex

  zilean:
    image: ipromknight/zilean:v1.5.3
    restart: unless-stopped
    container_name: zilean
    ports:
      - "8181:8181"
    volumes:
      - zilean_data:/app/data
    environment:
        Zilean__Database__ConnectionString: "Host=zilean-postgres;Port=5432;Database=zilean;Username=postgres;Password=postgres"
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8181/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10
    depends_on:
      zilean-postgres:
        condition: service_healthy

  zilean-postgres:
    image: postgres:16.3-alpine3.20
    container_name: zilean-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zilean
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - zilean_pg_data:/var/lib/postgresql/data/pgdata

volumes:
  zurg_data:
  zilean_data:
  elastic_data:
