# <- processor ->

# Override the minimum age before a scan request is sent to the target (Default 10m):
minimum-age: 0m

# Override the delay between processed scans (Default 5s):
scan-delay: 5s

# override the interval scan stats are displayed (defaults to 1 hour / 0s to disable):
scan-stats: 1h

# Set anchor files for remote storage. If these are missing no scans will be sent to the target to avoid files being trashed when a mount fails
anchors:
  - /data/realdebrid-zurg/version.txt

# <- triggers ->

# Optionally, protect your webhooks with authentication
authentication:
  username: 
  password: 

# Port for Autoscan webhooks to listen on
port: 3030

triggers:
  sonarr:
    - name: sonarr # /triggers/sonarr
      priority: 1
      
  radarr:
    - name: radarr # /triggers/radarr
      priority: 1

targets:
  plex:
    - url: http://URL_TO_PLEX
      token: PLEX_TOKEN
